### ISSUE TITLE
On Mac save app in applications folder

### ISSUE THREAD

**Issue by jesse-windebank** [michal-kapala/jitterbit-extractor#3]
For completeness, all Mac apps get saved in the following path:

![2023-11-09_06-22-24](https://github.com/michal-kapala/jitterbit-extractor/assets/60115932/12f4866a-cec2-4816-b366-d34869cef08f)

Instead of currently, the app is stored here:

![2023-11-09_06-21-27](https://github.com/michal-kapala/jitterbit-extractor/assets/60115932/6a89305e-83f6-489a-865a-88ffe4b1ca4a)

**Comment by michal-kapala** [comment]
Once you build the executable it is fully standalone, you can move it from `<repo root>/build/bin` to wherever you want

**Comment by jesse-windebank** [comment]
All good. I wasn't sure whether this was possible as a part of a param with wails. It appears not a simple post-install bash script does the job!
